openapi: 3.0.2
info:
  description: Tilgjengliggjoer noekkeltall fra virksomheters aarsregnskap
  version: '1.0'
  title: Regnskapsregisteret API
  contact:
    name: Broennoeysundregistrene
    url: 'https://fellesdatakatalog.brreg.no'
    email: fellesdatakatalog@brreg.no
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
tags:
  - name: regnskapsregisteret
    description: Regnskapsregister API
servers:
  - url: 'https://data.brreg.no/regnskapsregisteret'
paths:
  /regnskap:
    get:
      tags:
        - regnskap
      summary: Query for regnskaps.
      description: Returnerer en samling aarsregnskap
      operationId: getRegnskap
      parameters:
        - name: orgNummer
          in: query
          description: Virksomhetens organisasjonsnummer
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Regnskap'
        '404':
          description: Ikke funnet
  /regnskaps/{id}:
    get:
      tags:
        - regnskap
      description: Hent et spesifikt aarsregnskap for en virksomhet
      operationId: getRegnskapById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Regnskap"
        '404':
          description: Ikke funnet
components:
  schemas:
    Regnskap:
        type: object
        description: Et regnskap for et gitt aar
        properties:
          id:
            type: string
            description: system-generert id (GUID)
          virksomhet:
            $ref: "#/components/schemas/Virksomhet"
          regnskapsperiode:
            $ref: "#/components/schemas/Tidsperiode"
          valuta:
            $ref: "#/components/schemas/Valutakode"
          avviklingsregnskap:
            type: boolean
          oppstillingsplan:
            type: string
            enum:
            - smaa
            - store
            - oevrige
          revisjon:
            $ref: "#/components/schemas/Revisjon"
          regnkapsprinsipper:
            $ref: "#/components/schemas/Regnskapsprinsipper"
          egenkapitalGjeld:
            $ref: "#/components/schemas/EgenkapitalGjeld"
          eiendeler:
            $ref: "#/components/schemas/Eiendeler"
          resultatregnskapResultat:
            $ref: "#/components/schemas/ResultatregnskapResultat"
    ResultatregnskapResultat:
      type: object
      description: bladibladibla
      externalDocs:
        description: Begrepsreferanse
        url: https://jira.brreg.no/browse/BEGREP-821
      properties:
        ordinaertResultatFoerSkattekostnad:
          type: number
        aarsresultat:
          type: number
        totalresultat:
          type: number
        finansresultat:
          $ref: "#/components/schemas/Finansresultat"
        driftsresultat:
          $ref: "#/components/schemas/Driftsresultat"
    EgenkapitalGjeld:
      type: object
      properties:
        sumEgenkapitalGjeld:
            type: number
        egenkapital:
            $ref: "#/components/schemas/Egenkapital"
        gjeldOversikt:
            $ref: "#/components/schemas/Gjeld"
    Eiendeler:
      type: object
      properties:
        sumEiendeler:
            type: number
        omloepsmidler:
            $ref: "#/components/schemas/Omloepsmidler"
        anleggsmidler:
            $ref: "#/components/schemas/Anleggsmidler"
    Anleggsmidler:
      type: object
      properties:
        sumAnleggsmidler:
          type: number
    Omloepsmidler:
      type: object
      properties:
        sumOmloepsmidler:
          type: number
    Finansresultat:
      type: object
      properties:
        nettoFinans:
          type: number
        finansinntekt:
          $ref: "#/components/schemas/Finansinntekt"
        finanskostnad:
          $ref: "#/components/schemas/Finanskostnad"
    Driftsresultat:
      type: object
      properties:
        driftsresultat:
          type: number
        driftsinntekter:
          $ref: "#/components/schemas/Driftsinntekter"
        driftskostnad:
          $ref: "#/components/schemas/Driftskostnad"
    Driftsinntekter:
      type: object
      properties:
        sumDriftsinntekter:
          type: number
    Driftskostnad:
      type: object
      properties:
        sumDriftskostnad:
          type: number
    Finansinntekt:
      type: object
      properties:
        sumFinansinntekter:
          type: number
    Finanskostnad:
      type: object
      properties:
        sumFinanskostnad:
          type: number
    Virksomhet:
      type: object
      description: Virksomheten som regnskapet tilhoerer
      properties:
        organisasjonsnummer:
          type: string
        organisasjonsform:
          type: string
        morselskap:
          type: boolean
    Tidsperiode:
      type: object
      properties:
        fraDato:
          type: string
          format: date
        tilDato:
          type: string
          format: date
    Valutakode:
      type: string
    Revisjon:
      type: object
      properties:
        ikkeRevidertAarsregnskap:
          type: boolean
    Regnskapsprinsipper:
      type: object
    Egenkapital:
      type: object
      properties:
        sumEgenkapital:
          type: number
        opptjentEgenkapital:
          $ref: "#/components/schemas/OpptjentEgenkapital"
        innskuttEgenkapital:
          $ref: "#/components/schemas/InnskuttEgenkapital"
    OpptjentEgenkapital:
      type: object
      properties:
        sumOpptjentEgenkapital:
          type: number
    InnskuttEgenkapital:
      type: object
      properties:
        sumInnskuttEgenkaptial:
          type: number
    Gjeld:
      type: object
      properties:
        sumGjeld:
          type: number
        kortsiktigGjeld:
          $ref: "#/components/schemas/KortsiktigGjeld"
        langsiktigGjeld:
          $ref: "#/components/schemas/LangsiktigGjeld"
    KortsiktigGjeld:
      type: object
      properties:
        sumKortsiktigGjeld:
          type: number
    LangsiktigGjeld:
      type: object
      properties:
        sumLangsiktigGjeld:
          type: number
